runtime: python311
instance_class: F1
service: hercules-api-oauth2
entrypoint: gunicorn -w 2 -k uvicorn.workers.UvicornWorker pjecz_hercules_api_oauth2.main:app
env_variables:
  PROJECT_ID: justicia-digital-gob-mx
  SERVICE_PREFIX: pjecz_hercules_api_oauth2
vpc_access_connector:
  name: projects/justicia-digital-gob-mx/locations/us-west2/connectors/cupido
